require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - Steepfile

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 128
  AllowedPatterns: ['(\A|\s)#']

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 16

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 12

Naming/MethodParameterName:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleMemoizedHelpers:
  Max: 16
